sinclude $(TOPDIR)/config.mk

#LIB := $(obj)libao.a

obj-y += amp.o
obj-y += aiao_hal.o
obj-y += ao.o

#COBJS	:= $(COBJS-y)
#SRCS	:= $(COBJS:.o=.c)
#OBJS	:= $(addprefix $(obj),$(COBJS))

#all:	$(LIB)

#$(LIB):	$(obj).depend $(OBJS)
#	$(AR) $(ARFLAGS) $@ $(OBJS)

#########################################################################

# defines $(obj).depend target
#include $(SRCTREE)/rules.mk

#sinclude $(obj).depend

#########################################################################

