#include $(TOPDIR)/config.mk

#LIBS := $(obj)libvo.a

obj-y += vou.o
obj-y += vou_drv.o
obj-y += vou_hal.o
obj-y += vou_coef_org.o

#COBJS	:= $(COBJS-y)
#SRCS	:= $(COBJS:.o=.c)
#OBJS	:= $(addprefix $(obj),$(COBJS))

#all:	$(LIBS)

#$(LIBS):	$(obj).depend $(OBJS)
#	$(AR) $(ARFLAGS) $@ $(OBJS)

#########################################################################

# defines $(obj).depend target
#Einclude $(SRCTREE)/rules.mk

#sinclude $(obj).depend

#########################################################################

