#
# Copyright (c) 2017 HiSilicon Technologies Co., Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-$(CONFIG_HI35XX_COMMON)	+= init_regs.o uart.o soc.o util.o
extra-$(CONFIG_HIMCI)	+= himci_boot.o
obj-y	+= dummy.o


